[provide general introduction to the issue logging and why it is relevant to this repository]

## Type Of Issue

[] Bug
[] New Request
[] any other

## Context

[provide more detailed introduction to the issue itself and why it is relevant]

## Process

[ordered list the process to finding and recreating the issue, example below]

1.
2.
3.

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you you currently experience from this process, and thereby explain the bug]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

* 
*

## `name of issue` screenshot

[if relevant, include a screenshot]