name: Publish Docker image to Docker Hub

on:
  push:
    branches: [opensurce]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Read Version
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION
      - name: Echo VERSION
        run: echo "${{ steps.package.outputs.content }}"
        
      - name: Docker Login
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $username -p $password
    
      - name: Build the Docker Image
        run: |
           docker build . --file Dockerfile --tag yashwanthmoengage/alarms-checker:${{ steps.package.outputs.content }} 
           docker build . --file Dockerfile --tag yashwanthmoengage/alarms-checker:latest
    
      - name: Docker Push
        run: |
          docker push yashwanthmoengage/alarms-checker:${{ steps.package.outputs.content }}  
          docker push yashwanthmoengage/alarms-checker:latest 
